import { test, expect } from "@playwright/test";
import { LoginPage } from "./pages/LoginPage";
import { JobsPage } from "./pages/JobsPage";
import { JobDetailPage } from "./pages/JobDetailPage";
import { JobApplicationPage } from "./pages/JobApplicationPage";
import { SavedJobsPage } from "./pages/SavedJobsPage";
import { ProfilePage } from "./pages/ProfilePage";
import { execSync } from "child_process";

test.beforeAll(() => {
  console.log("Running DB seed and cleanup...");
  execSync("npx tsx scripts/seed-test-users.ts", { stdio: "inherit" });
});

test.describe("Authenticated User Flows", () => {
  let loginPage: LoginPage;
  let jobsPage: JobsPage;
  let jobDetailPage: JobDetailPage;
  let jobApplicationPage: JobApplicationPage;
  let savedJobsPage: SavedJobsPage;
  let profilePage: ProfilePage;

  test.beforeEach(async ({ page }) => {
    loginPage = new LoginPage(page);
    jobsPage = new JobsPage(page);
    jobDetailPage = new JobDetailPage(page);
    jobApplicationPage = new JobApplicationPage(page);
    savedJobsPage = new SavedJobsPage(page);
    profilePage = new ProfilePage(page);

    await loginPage.navigate();
    await loginPage.submitLoginForm("seeker@mrowka.pl", "Password123!");

    await expect(page).toHaveURL("/", { timeout: 15000 });
  });

  test("Job Seeker Happy Path: Save job, apply, and edit profile", async ({
    page,
  }) => {
    test.setTimeout(60000);

    // 1. Navigate to Jobs
    await jobsPage.navigate();
    await jobsPage.waitForLoad();

    expect(await jobsPage.hasJobsLoaded()).toBe(true);
    await jobsPage.jobOfferLinks.first().click();
    await jobDetailPage.verifyVisible();

    // 2. Save the job
    const saveButton = page.getByRole("button", { name: /Save Job|Saved/i });
    if (await saveButton.isVisible()) {
      await saveButton.click();
    }

    // 3. Apply for the job
    await jobDetailPage.clickApply();
    await expect(page).toHaveURL(/\/jobs\/apply\/.*/, { timeout: 15000 });

    await jobApplicationPage.fillCoverLetter(
      "Hello, this is my automated cover letter generated by Playwright E2E tests!",
    );
    await jobApplicationPage.submitApplication();
    await jobApplicationPage.verifySuccess();

    const alreadyAppliedBtn = page.getByText("Already applied");
    await expect(alreadyAppliedBtn.first()).toBeVisible({ timeout: 10000 });

    // 4. Verify it appears in Saved Jobs
    await savedJobsPage.navigate();
    await savedJobsPage.verifyVisible();
    await savedJobsPage.verifyJobIsSaved();

    // 5. Edit Profile
    await profilePage.navigate();
    await profilePage.verifyVisible();
    await profilePage.updateProfile("+1234567890", "Playwright University");
    await profilePage.verifySuccess();
  });
});
